# Generated by Django 3.2.3 on 2023-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vids',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Products'),
        ),
    ]
