# Generated by Django 3.2.3 on 2023-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='searches',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='words',
            field=models.IntegerField(default=5000),
        ),
    ]
