# Generated by Django 3.2.3 on 2023-04-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store_name',
        ),
    ]
