# Generated by Django 3.2.3 on 2023-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230314_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='words',
            field=models.IntegerField(default=2000),
        ),
    ]
