# Generated by Django 3.2.3 on 2023-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_order_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Store Name'),
        ),
    ]
