# Generated by Django 3.2.3 on 2023-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_external_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submited', 'Submited'), ('fulfilled', 'FulFilled')], default='pending', max_length=20),
        ),
    ]
