# Generated by Django 3.2.3 on 2023-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Store Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submited', 'Submited'), ('fulfilled', 'FulFilled')], default='Pending', max_length=20),
        ),
    ]
