# Generated by Django 3.2.3 on 2023-05-15 18:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('free', 'free'), ('basic', 'basic'), ('premium', 'premium'), ('moderator', 'moderator')], default='free', max_length=100)),
                ('words', models.IntegerField(default=5000)),
                ('searches', models.IntegerField(default=25)),
                ('ebay_access_token', models.TextField(blank=True, default='', verbose_name='Ebay Access Token')),
                ('facebook_user_id', models.TextField(blank=True, default='', verbose_name='Facebook User ID')),
                ('facebook_page_id', models.TextField(blank=True, default='', verbose_name='Facebook Page ID')),
                ('instagram_user_id', models.TextField(blank=True, default='', verbose_name='Instagram User ID')),
                ('facebook_access_token', models.TextField(blank=True, default='', verbose_name='Facebook Access Token')),
                ('store_type', models.CharField(choices=[('none', 'None'), ('woocommerce', 'WooCommerce'), ('shopify', 'Shopify')], default='none', max_length=20)),
                ('store_name', models.TextField(blank=True, default='', verbose_name='Store name')),
                ('woocommerce_store_name', models.TextField(blank=True, default='', verbose_name='WooCommerce store name')),
                ('woocommerce_host', models.TextField(blank=True, default='', verbose_name='WooCommerce store domain')),
                ('woocommerce_consumer_key', models.TextField(blank=True, default='', verbose_name='WooCommerce consumer key')),
                ('woocommerce_secret_key', models.TextField(blank=True, default='', verbose_name='WooCommerce secret key')),
                ('shopify_store_name', models.TextField(blank=True, default='', verbose_name='Shopify store name')),
                ('shopify_host', models.TextField(blank=True, default='', verbose_name='Shopify store domain')),
                ('shopify_consumer_key', models.TextField(blank=True, default='', verbose_name='Shopify consumer key')),
                ('shopify_secret_key', models.TextField(blank=True, default='', verbose_name='Shopify secret key')),
                ('cjdropshipping_email', models.TextField(blank=True, default='', verbose_name='CJDropshipping Email')),
                ('cjdropshipping_api_key', models.TextField(blank=True, default='', verbose_name='CJDropshipping API Key')),
                ('description', models.TextField(blank=True, default='', max_length=600, verbose_name='Description')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('api_version', models.TextField(blank=True, default='')),
                ('amount_subtotal', models.TextField(blank=True, default='')),
                ('amount_total', models.TextField(blank=True, default='')),
                ('billing_address_collection', models.TextField(blank=True, default='')),
                ('cancel_url', models.TextField(blank=True, default='')),
                ('created', models.TextField(blank=True, default='')),
                ('currency', models.TextField(blank=True, default='')),
                ('customer', models.TextField(blank=True, default='')),
                ('customer_creation', models.TextField(blank=True, default='')),
                ('customer_email', models.TextField(blank=True, default='')),
                ('expires_at', models.TextField(blank=True, default='')),
                ('session_id', models.TextField(blank=True, default='', primary_key=True, serialize=False)),
                ('invoice', models.TextField(blank=True, default='')),
                ('livemode', models.TextField(blank=True, default='')),
                ('mode', models.TextField(blank=True, default='')),
                ('object_type', models.TextField(blank=True, default='')),
                ('payment_method_collection', models.TextField(blank=True, default='')),
                ('payment_method_types', models.TextField(blank=True, default='')),
                ('payment_status', models.TextField(blank=True, default='')),
                ('phone_number_collection', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('subscription', models.TextField(blank=True, default='')),
                ('success_url', models.TextField(blank=True, default='')),
                ('total_details', models.TextField(blank=True, default='')),
                ('session_type', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.TextField(blank=True, default='', max_length=10000, verbose_name='External order id:')),
                ('store_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Store Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submited', 'Submited'), ('fulfilled', 'FulFilled')], default='Pending', max_length=20)),
                ('order_info', models.TextField(blank=True, default='', max_length=10000, verbose_name='Full JSON response:')),
                ('shipping_zip', models.CharField(blank=True, default='', max_length=10, verbose_name='Shipping Zip')),
                ('shipping_country_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Shipping Country Code')),
                ('shipping_country', models.CharField(blank=True, default='', max_length=100, verbose_name='Shipping Country')),
                ('shipping_province', models.CharField(blank=True, default='', max_length=100, verbose_name='Shipping Province')),
                ('shipping_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Shipping City')),
                ('shipping_address', models.TextField(blank=True, default='', max_length=500, verbose_name='Shipping Address')),
                ('shipping_customer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Shipping Customer Name')),
                ('shipping_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Shipping Phone')),
                ('remark', models.TextField(blank=True, default='', max_length=500, verbose_name='Remark')),
                ('from_country_code', models.CharField(blank=True, default='', max_length=10, verbose_name='From Country Code')),
                ('logistic_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Logistic Name')),
                ('products', models.TextField(blank=True, default='', max_length=1000, verbose_name='Products')),
                ('vids', models.TextField(blank=True, default='', max_length=1000, verbose_name='Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField(blank=True, default='', verbose_name='timestamp')),
                ('status', models.TextField(choices=[('pending', 'pending'), ('failed', 'failed'), ('succed', 'succed')], default='pending', max_length=20)),
                ('lookup_key', models.TextField(default='', verbose_name='lookup key')),
                ('session_id', models.TextField(blank=True, default='', verbose_name='session if')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_contract_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
