# Generated by Django 3.2.3 on 2023-03-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_inventoryitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='descriptionWritesonic_1',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='descriptionWritesonic_2',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='descriptionWritesonic_3',
        ),
    ]
