# Generated by Django 3.2.3 on 2023-04-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_inventoryitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='descriptionChatGpt',
            new_name='descriptionCustom',
        ),
    ]
